//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureStore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int Check_number { get; set; }
        public int Seller_number { get; set; }
        public System.DateTime Date_of_sale { get; set; }
    }
}
