//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureStore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public int Seller_number { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthday { get; set; }
        public System.DateTime Date_of_receipt { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    }
}
